UserBundle\Entity\Ip:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\IpRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
        ipAddress:
            type: string
            length: '20'
            unique: true
            column: ip_address
    lifecycleCallbacks: {  }
