parameters:
  user.login_listener.class: UserBundle\EventListener\LoginListener

services:
  authentication.handler.login_success_handler:
    class:  UserBundle\Security\LoginSuccessHandler
    arguments:  ['@router', '@security.authorization_checker']
  user.login_listener:
    class: %user.login_listener.class%
    arguments:
      userManager: "@fos_user.user_manager"
      entityManager: "@doctrine.orm.entity_manager"
    tags:
     - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }