parameters:
  user.login_listener.class: UserBundle\EventListener\LoginListener

services:
  user.login_listener:
    class: %user.login_listener.class%
    arguments:
      userManager: "@fos_user.user_manager"
      entityManager: "@doctrine.orm.entity_manager"
      #userLogin: "@user.user_login"
    tags:
     - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }